version: '3.5'

services:
  app:
    container_name: app
    ports:
      - "50201:80"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
    networks:
      - jivo_bot_network
      - jivo_bot_redis_network
    command: [ "sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 80 --reload" ]
    restart: always
  db:
    restart: always
    image: postgres:15.3
    ports:
      - "50202:5432"
    volumes:
      - jivo_bot_db_data:/var/lib/postgresql/data
    networks:
      - jivo_bot_network
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=test
  redis:
    container_name: redis
    restart: always
    image: redis:7.0.8
    networks:
      - jivo_bot_redis_network

networks:
  jivo_bot_network:
  jivo_bot_redis_network:

volumes:
  jivo_bot_db_data:
